name: 'Assign reviewer by roster'
description: 'Assigns reviewers by roster. They alternate per sprint.'
inputs:
  token:
    description: 'Token for octokit'
    required: true
outputs:
  reviewers:
    description: Reviewers that were assigned
runs:
  using: 'node12'
  main: 'index.js'