name: Assign reviewer by roster

on:
  pull_request:
    types: [ opened, reopened ]
    branches:
      - develop

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v1
      - name: Log all files in folder
        run: |
          pwd
          ls -a
      - name: Install base modules
        run: |
          npm i -D @actions/core
          npm i -D @actions/github
      - name: Hello world action step
        id: hello
        uses: ./.github/actions/assignReviewerByRoster
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"