name: Assign reviewer by roster

on:
  pull_request:
    types: [ opened, reopened ]
    branches:
      - develop

jobs:
  assign_reviewer_job:
    runs-on: ubuntu-latest
    name: A to assign reviewers to PR
    steps:
      - uses: actions/checkout@v1
      - name: Log all files in folder
        run: |
          pwd
          ls -a
      - name: Install base modules
        run: |
          npm i -D @actions/core
          npm i -D @actions/github
      - name: Reviewer(s) assignment
        id: reviewerAssignment
        uses: ./.github/actions/assignReviewerByRoster
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT: ${{ toJSON(github) }}
      - name: Display the assigned reviewers
        run: echo "The assigned reviewers are ${{ steps.reviewerAssignment.outputs.reviewers }}"