name: Node.js CI

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: node:lastest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: seaqull
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Run tests
        working-directory: ./backend
        run: |
          mv ormconfig.example.json ormconfig.json
          npm install
          npm run reset
          npm start
          npm test
        env:
          JWT_SECRET: KGn]FCx0w~TI
          JWT_EXPIRATION_TIME: 600000
          RECAPTCHA_SECRET_KEY: 6LcuZr8cAAAAAFprJpiETSZ84zOK35JAb8EhGyKs
          secure: false
          PORT: 8000
          NODE_ENV: development
          CURRENT_APP_STATE: dev
          HCAPTCHA_DEV_SECRET_KEY: 0x0000000000000000000000000000000000000000